In [5]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df = pd.read_csv('emotion predic for NLP.txt',sep = ';',header = None,names = ['text','emotion'])  # as csv file seprate by ';'
                                                        #header = None beacuse we do not want that 1st value will be header, so we put manullay header name

In [7]:
df.head()

                                                text  emotion
0  im feeling rather rotten so im not very ambiti...  sadness
1          im updating my blog because i feel shitty  sadness
2  i never make her separate from me because i do...  sadness
3  i left with my bouquet of red and yellow tulip...      joy
4    i was feeling a little vain when i did this one  sadness

In [8]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [9]:
unique_emotions = df['emotion'].unique()   # To see unique values of emotion
emotion_num = {} ## Now we want to label those unique values
i = 0
for emotion in unique_emotions:
    emotion_num[emotion] = i
    i += 1
df['emotion'] = df['emotion'].map(emotion_num)
df

                                                   text  emotion
0     im feeling rather rotten so im not very ambiti...        0
1             im updating my blog because i feel shitty        0
2     i never make her separate from me because i do...        0
3     i left with my bouquet of red and yellow tulip...        1
4       i was feeling a little vain when i did this one        0
...                                                 ...      ...
1995  i just keep feeling like someone is being unki...        3
1996  im feeling a little cranky negative after this...        3
1997  i feel that i am useful to my people and that ...        1
1998  im feeling more comfortable with derby i feel ...        1
1999  i feel all weird when i have to meet w people ...        2

[2000 rows x 2 columns]

# Step 1 : Lower casing

In [10]:
df['text'] = df['text'].apply(lambda x: x.lower())

# Step 2 : Remove punctuation

In [11]:
import string
def remove_punctuation(text):
    for punc in string.punctuation:
        text = text.replace(punc,'')
    return text
df['text'] = df['text'].apply(remove_punctuation)

# Step 3 : Remove NUmbers

In [12]:
def remove_numbers(text):
    text = ''.join(word for word in text if not word.isdigit())
    return text
df['text'] = df['text'].apply(remove_numbers)

# Step 4 : Remove Url

In [13]:
# There has no url so we can skip the part for the data set

# Step 5: Remove Emojis & Special Char

In [14]:
# Every emoji has a unique code or ascy values , so we need to find those and remove

In [15]:
def remove_emojis(txt):
  new =""
  for i in txt:
    if i.isascii():
      new+=i
  return new
df['text'] = df['text'].apply(remove_emojis)

# Step 7 : Remove Stopwords

In [16]:
# For removing stopwords like 'is','the','are',...etc  we have to uselibray that is NLTK (Natural language tool kit ) (use for data preprocessing) see in datils in google

In [17]:
import nltk

# Those things need also to mremove Stopwords
# Corpus (see detals in google)
# sentence
#Token

In [18]:

from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [19]:
nltk.download('stopwords')  # Stopwords you know
nltk.download('punkt')  # Use for tokenization

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.

True

In [20]:
stop_words = set(stopwords.words('english')) # Import all stiopwords  # we use more in DL

In [21]:
stop_words

{'a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 "he's",
 'her',
 'here',
 'hers',
 'herself',
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 "i'll",
 "i'm",
 "i've",
 'if',
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'only',
 'or',
 'other',
 'our',
 'ours',
 'ourselves',
 'out',
 'over',
 'own',
 're',
 's',
 'same',
 'shan',
 "shan't",
 'she',
 "she'd",
 "she'll",
 "she's",
 'should',
 "should've",
 'shouldn',
 "shouldn't",
 'so',
 'some',
 'such',
 't',
 'than',
 'that',
 "that'll",
 'the',
 'their',
 'theirs',
 'them',
 'themselves',
 'then',
 'there',
 'these',
 'they',
 "they'd",
 "they'll",
 "they're",
 "they've",
 'this',
 'those',
 'through',
 'to',
 'too',
 'under',
 'until',
 'up',
 've',
 'very',
 'was',
 'wasn',
 "wasn't",
 'we',
 "we'd",
 "we'll",
 "we're",
 "we've",
 'were',
 'weren',
 "weren't",
 'what',
 'when',
 'where',
 'which',
 'while',
 'who',
 'whom',
 'why',
 'will',
 'with',
 'won',
 "won't",
 'wouldn',
 "wouldn't",
 'y',
 'you',
 "you'd",
 "you'll",
 "you're",
 "you've",
 'your',
 'yours',
 'yourself',
 'yourselves'}

In [22]:
len(stop_words)  # 198 stopwords total

198

In [23]:
df.loc[1]['text']

'im updating my blog because i feel shitty'

In [24]:
# from here we need to remove stopwords and convert to an array and list

In [25]:
# Then we need to tokenize

In [26]:
def remove(txt):
  words = txt.split()  # use  split beacuse word_tokenize is not working here
  new_words = []
  for word in words:
    if word not in stop_words:
      new_words.append(word)
  return ' '.join(new_words)

In [27]:
df['text'] = df['text'].apply(remove)

In [28]:
df.loc[1]['text']  # Now you can see the sentence after remove stopwords

'im updating blog feel shitty'

# Next part of complete all lesson (Last part of video)

In [30]:
from sklearn.model_selection import train_test_split   # Do train test split

X_train, X_test, y_train, y_test = train_test_split(df['text'], df['emotion'], test_size=0.33, random_state=42)

In [31]:
X_train.shape

(1340,)

In [32]:
X_test.shape

(660,)

In [33]:
df.shape

(2000, 2)

# Convert text to Vector for ML

In [34]:
# Here we use bag of words and TF-IDF ,then we will see what will give best ans

In [36]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer # Import count.. for bag of vector and tfid .. is for TF_IDF vetorize

In [37]:
# Bag or words

In [41]:
bow_vectorizer = CountVectorizer()
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [40]:
X_train_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 12214 stored elements and shape (1340, 3756)>

In [42]:
X_test_bow

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 4833 stored elements and shape (660, 3756)>

# Use Naive byes ML model

In [44]:
from sklearn.naive_bayes import MultinomialNB  # You can search which naive byes use for the project , as there has many naive byes as like gaussian

In [45]:
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix  #To see accuracy score

In [47]:
nb_model = MultinomialNB()
nb_model.fit(X_train_bow,y_train)

MultinomialNB()

In [48]:
y_pred = nb_model.predict(X_test_bow)
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.6181818181818182
              precision    recall  f1-score   support

           0       0.61      0.82      0.70       207
           1       0.60      0.88      0.72       223
           2       0.81      0.24      0.37        71
           3       0.73      0.30      0.42        80
           4       0.67      0.04      0.07        57
           5       0.00      0.00      0.00        22

    accuracy                           0.62       660
   macro avg       0.57      0.38      0.38       660
weighted avg       0.63      0.62      0.56       660

[[169  33   1   4   0   0]
 [ 25 196   0   1   1   0]
 [ 29  23  17   2   0   0]
 [ 32  23   1  24   0   0]
 [ 20  33   1   1   2   0]
 [  4  16   1   1   0   0]]

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [49]:
# TF -IDF

In [52]:
tfidf_vectorizer = TfidfVectorizer()
X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)
X_test_tfidf = tfidf_vectorizer.transform(X_test)

In [53]:
               # use nave byas 1st in IF-IDF

In [54]:
nb2_model = MultinomialNB()
nb2_model.fit(X_train_tfidf,y_train)

MultinomialNB()

In [56]:
y_pred = nb2_model.predict(X_test_tfidf)

In [57]:
print(accuracy_score(y_test,y_pred))
print(classification_report(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.55
              precision    recall  f1-score   support

           0       0.67      0.69      0.68       207
           1       0.49      0.97      0.65       223
           2       1.00      0.04      0.08        71
           3       1.00      0.01      0.02        80
           4       0.00      0.00      0.00        57
           5       0.00      0.00      0.00        22

    accuracy                           0.55       660
   macro avg       0.53      0.29      0.24       660
weighted avg       0.60      0.55      0.44       660

[[142  65   0   0   0   0]
 [  6 217   0   0   0   0]
 [ 22  46   3   0   0   0]
 [ 25  54   0   1   0   0]
 [ 14  43   0   0   0   0]
 [  2  20   0   0   0   0]]

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [58]:
             # LOgistic regression i If-IDF

In [59]:
from sklearn.linear_model import LogisticRegression

In [60]:
logistic_model = LogisticRegression(max_iter=1000) # max_iterion is 1000 for vector aize will be big in that type of project
logistic_model.fit(X_train_tfidf,y_train)

LogisticRegression(max_iter=1000)

In [61]:
log_pred = logistic_model.predict(X_test_tfidf)

In [62]:
print(accuracy_score(y_test,log_pred))
print(classification_report(y_test,log_pred))
print(confusion_matrix(y_test,log_pred))

0.6212121212121212
              precision    recall  f1-score   support

           0       0.68      0.75      0.71       207
           1       0.55      0.95      0.70       223
           2       0.81      0.30      0.43        71
           3       0.90      0.24      0.38        80
           4       1.00      0.05      0.10        57
           5       0.00      0.00      0.00        22

    accuracy                           0.62       660
   macro avg       0.66      0.38      0.39       660
weighted avg       0.68      0.62      0.56       660

[[155  50   1   1   0   0]
 [ 10 212   1   0   0   0]
 [ 18  32  21   0   0   0]
 [ 21  40   0  19   0   0]
 [ 18  36   0   0   3   0]
 [  5  13   3   1   0   0]]

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [63]:
 # svm

In [65]:
from sklearn.svm import SVC

In [66]:
svm_model = SVC()
svm_model.fit(X_train_tfidf,y_train)

SVC()

In [67]:
svm_pred = svm_model.predict(X_test_tfidf)

In [68]:
print(accuracy_score(y_test,svm_pred))
print(classification_report(y_test,svm_pred))
print(confusion_matrix(y_test,svm_pred))

0.5484848484848485
              precision    recall  f1-score   support

           0       0.72      0.60      0.66       207
           1       0.46      0.96      0.63       223
           2       0.93      0.18      0.31        71
           3       0.88      0.09      0.16        80
           4       1.00      0.04      0.07        57
           5       0.00      0.00      0.00        22

    accuracy                           0.55       660
   macro avg       0.67      0.31      0.30       660
weighted avg       0.68      0.55      0.48       660

[[125  82   0   0   0   0]
 [  8 215   0   0   0   0]
 [ 12  46  13   0   0   0]
 [ 15  58   0   7   0   0]
 [  9  46   0   0   2   0]
 [  4  16   1   1   0   0]]

/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.13/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))